(function() {var implementors = {};
implementors["juice"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"juice/layers/common/linear/struct.Linear.html\" title=\"struct juice::layers::common::linear::Linear\">Linear</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"juice/layers/common/log_softmax/struct.LogSoftmax.html\" title=\"struct juice::layers::common::log_softmax::LogSoftmax\">LogSoftmax</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"juice/layers/common/softmax/struct.Softmax.html\" title=\"struct juice::layers::common::softmax::Softmax\">Softmax</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"juice/layers/container/sequential/struct.SequentialConfig.html\" title=\"struct juice::layers::container::sequential::SequentialConfig\">SequentialConfig</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"juice/solver/struct.SolverConfig.html\" title=\"struct juice::solver::SolverConfig\">SolverConfig</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"juice/weight/struct.WeightConfig.html\" title=\"struct juice::weight::WeightConfig\">WeightConfig</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
