(function() {var implementors = {};
implementors["juice"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"juice/layers/common/pooling/enum.PoolingMode.html\" title=\"enum juice::layers::common::pooling::PoolingMode\">PoolingMode</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"juice/solver/confusion_matrix/struct.Sample.html\" title=\"struct juice::solver::confusion_matrix::Sample\">Sample</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"juice/solver/confusion_matrix/struct.Accuracy.html\" title=\"struct juice::solver::confusion_matrix::Accuracy\">Accuracy</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"juice/solver/enum.SolverKind.html\" title=\"enum juice::solver::SolverKind\">SolverKind</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"juice/solver/enum.SGDKind.html\" title=\"enum juice::solver::SGDKind\">SGDKind</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"juice/solver/enum.LRPolicy.html\" title=\"enum juice::solver::LRPolicy\">LRPolicy</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"juice/solver/enum.RegularizationMethod.html\" title=\"enum juice::solver::RegularizationMethod\">RegularizationMethod</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"juice/weight/enum.DimCheckMode.html\" title=\"enum juice::weight::DimCheckMode\">DimCheckMode</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"juice/weight/enum.FillerType.html\" title=\"enum juice::weight::FillerType\">FillerType</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
