(function() {var implementors = {};
implementors["juice"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"enum\" href=\"juice/layer/enum.LayerType.html\" title=\"enum juice::layer::LayerType\">LayerType</a>&gt; for <a class=\"struct\" href=\"juice/layers/common/convolution/struct.ConvolutionConfig.html\" title=\"struct juice::layers::common::convolution::ConvolutionConfig\">ConvolutionConfig</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"enum\" href=\"juice/layer/enum.LayerType.html\" title=\"enum juice::layer::LayerType\">LayerType</a>&gt; for <a class=\"struct\" href=\"juice/layers/common/linear/struct.LinearConfig.html\" title=\"struct juice::layers::common::linear::LinearConfig\">LinearConfig</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"enum\" href=\"juice/layer/enum.LayerType.html\" title=\"enum juice::layer::LayerType\">LayerType</a>&gt; for <a class=\"struct\" href=\"juice/layers/common/pooling/struct.PoolingConfig.html\" title=\"struct juice::layers::common::pooling::PoolingConfig\">PoolingConfig</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"enum\" href=\"juice/layer/enum.LayerType.html\" title=\"enum juice::layer::LayerType\">LayerType</a>&gt; for <a class=\"struct\" href=\"juice/layers/loss/negative_log_likelihood/struct.NegativeLogLikelihoodConfig.html\" title=\"struct juice::layers::loss::negative_log_likelihood::NegativeLogLikelihoodConfig\">NegativeLogLikelihoodConfig</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"enum\" href=\"juice/layer/enum.LayerType.html\" title=\"enum juice::layer::LayerType\">LayerType</a>&gt; for <a class=\"struct\" href=\"juice/layers/utility/reshape/struct.ReshapeConfig.html\" title=\"struct juice::layers::utility::reshape::ReshapeConfig\">ReshapeConfig</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"enum\" href=\"juice/layer/enum.LayerType.html\" title=\"enum juice::layer::LayerType\">LayerType</a>&gt; for <a class=\"struct\" href=\"juice/layers/container/sequential/struct.SequentialConfig.html\" title=\"struct juice::layers::container::sequential::SequentialConfig\">SequentialConfig</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
