[book]
title = "juice documentation"
description = "Introduction book to the juice framework"
authors = ["Bernhard Schuster <bernhard@ahoi.io>"]
authors = [
	"Maximilian Goisser <max@autumnai.com>",
	"Michael Hirn <mj@autumnai.com>",
	"Bernhard Schuster <bernhard@ahoi.io>",
]

language = "en"

[output.html]
mathjax-support = true

[output.html.playpen]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2